version: '3.1'

services:
  wordpress:
    depends_on:
      - mysql
    image: hardeepasrani/pirate-brewery
    ports:
      - 998:80
    volumes:
      - ./:/var/www/html/wp-content/mu-plugins
      - ./tests/sample-theme:/var/www/html/wp-content/themes/sample-theme
    restart: always
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_ROOT_PASSWORD: wordpress
  mysql:
    image: mysql:5.7
    volumes:
      - ~/db_data_onboarding:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
